enhance `ember install`
ember-cli/rfcs pull request #107
Opened 2017-05-25 13:01 UTC by kellyselden

2017-05-25 13:14 UTC, webark commented
would there need to be a corresponding "remove/uninstall" then?

2017-05-25 13:33 UTC, kellyselden commented
> would there need to be a corresponding "remove/uninstall" then?

No. Since there is already an install command without an uninstall command, that seems out of scope.

2017-05-25 13:53 UTC, buschtoens commented
Instead of erroring ember-cli should print a note, indicating to the user that the installed package is not an Ember add-on. 

> The package '${packageName}‘ is not an Ember add-on. In order to use it you'll probably need to perform some further custom setup.

2017-05-25 14:02 UTC, stefanpenner requested changes

2017-05-25 14:02 UTC, stefanpenner commented on active/0000-ember-install.md
> +# Detailed design
This needs to be fleshed out more. As the ember command will attempt to find the local ember, and sad things may happen.

This is worsened by partial node_module checkouts.

One approach would be for `ember install` to always fallback to the global `ember` installation?

2017-05-25 14:47 UTC, webark commented
ya. with the motivation being that ember-cli chooses to use yarn for you.. if you just npm uninstall won't the reference stay in your yarn.lock? i guess it wouldn't actually install the package later.. but just seems a little messy, and that ideally you're still going to have to keep track if your using yarn or npm5 (same with when pulling a project for the first time)

2017-05-25 15:55 UTC, kellyselden commented on active/0000-ember-install.md
> +# Detailed design
Wouldn't this just piggy-back on how `ember install package-name` finds the `ember` bin? Why would this RFC be focused on that resolution?

2017-05-25 15:57 UTC, kellyselden commented
@webark We already suffer from the problem that `ember install package-name` may modify your `yarn.lock`, but we have no `ember uninstall package-name`. Solving that would be the scope of a different RFC IMO.

2017-05-25 16:06 UTC, stefanpenner commented on active/0000-ember-install.md
> +# Detailed design
I think that is the trickiest bit to late this successfully.

2017-05-30 13:22 UTC, Turbo87 commented
FWIW I'm not in favor of this RFC. `ember install foobar` serves the purpose of installing the dep **and** running the corresponding blueprint, but everything else can just be installed without ember-cli having to care about it. I think making `ember install` and alias for `npm/yarn install` increases the amount of perceived magic done by the Ember ecosystem.

Regarding `ember install` should work for non-addons: I thought that already worked without any issues. If it doesn't I would consider it a bug that should be fixed.

2017-05-30 16:42 UTC, dbbk commented
> No. Since there is already an install command without an uninstall command, that seems out of scope.

I don't understand the reasoning behind this. If the goal is to make the use of `npm` or `yarn` 'invisible' to the end user, why would there not be a command to remove packages? It seems very unintuitive.

2019-01-19 19:46 UTC, rwjblue commented
We are working on closing the ember-cli/rfcs repo in favor of using a single central RFC's repo for everything. This was laid out in https://emberjs.github.io/rfcs/0300-rfc-process-update.html. 

Sorry for the troubles, but would you mind reviewing to see if this is still something we need, and if so migrating this over to emberjs/rfcs?

Thank you!

2019-01-19 19:46 UTC, closed without merging